Need to require more of active_support in order to have access to 1.days
Fix for:

  /usr/local/bundle/gems/activesupport-3.2.17/lib/active_support/core_ext/time/calculations.rb:193:in `beginning_of_week': undefined method `days' for 2:Fixnum (NoMethodError)
    from /usr/local/bundle/gems/thin_out_backups-0.0.4/lib/thin_out_backups.rb:95:in `start_time'