Add require 'active_support' to avoid getting error from require 'active_support/time' with Rails 7.1:
  NoMethodError:
    undefined method `deprecator' for ActiveSupport:Module

      deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                              ^^^^^^^^^^^