Remove dependency on quality_extensions/module/attribute_accessors
Apparently that file defines a mattr_accessor method that is slightly different than the one in
activesupport 4.2.1+ so it ended up causing an error like this when used with rails 4+ (I'd only been using it in rails 3 so far):

  SyntaxError: /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:9: `@@{' is not allowed as a class variable name
  /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:9: syntax error, unexpected end-of-input
          unless defined? @@{:instance_writer=>false, :in...
                            ^
  /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:8:in `class_eval'
  /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:8:in `block in mattr_reader'
  /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:7:in `each'
  /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:7:in `mattr_reader'
  /usr/local/bundle/gems/quality_extensions-1.4.0/lib/quality_extensions/module/attribute_accessors.rb:45:in `mattr_accessor'
  /usr/local/bundle/gems/actionview-4.2.1/lib/action_view/helpers/form_helper.rb:1938:in `block in <module:ActionView>'

The easy solution seems to be to stop using the version from quality_extensions (which was
overriding the version from activesupport) and to just use the version defined in
active_support/core_ext/module/attribute_accessors instead.

[Fixes #1]